### PR TITLE
add attachments in params of ticket api

### PR DESCRIPTION
**Pull request by hkhungit**

### CODE REVIEW

**Comment by nvhbk16k53** [comment]
It seems like you just add attachments parameter for `topic` and do nothing to support upload these attachments to `Helpy` server. Also, we need to support attachments for `post`.

**Comment by nvhbk16k53** [comment]
The scenario is: I want to create a post with attachment file `image.jpg`, how do I create post with `Helpy` API?

**Comment by hkhungit** [comment]
I updated attachments parameter for post api.
we  just put file into attachments parameter and carrierwave support up file to server.

**Comment by nvhbk16k53** [comment]
Can you write an example for client to create a post with attachments? Use `curl` or something else.

**Comment by hkhungit** [comment]
example for create a topic with attachments
curl -i -X POST -H "Content-Type: multipart/form-data" \\
-F "token=3add908c5b59b768751cc9f9ce794b3b" \\
-F "user_id=2" \\
-F "name=hello topic" \\
-F "body=hello world" \\
-F "attachments[]=@./moto.jpg" \\
http://localhost:3000/api/v1/tickets

example for create a posts with attachments
curl -i -X POST -H "Content-Type: multipart/form-data" \\
-F "token=3add908c5b59b768751cc9f9ce794b3b" \\
-F "user_id=2" \\
-F "topic_id=1" \\
-F "kind=first" \\
-F "name=hello topic" \\
-F "body=hello world" \\
-F "attachments[]=@./moto.jpg" \\
http://localhost:3000/api/v1/posts

**Comment by nvhbk16k53** [comment]
LGTM 👍

**Comment by metadoggo** [comment]
Nice once 👍 
One question: Why are the `keymono` fields part of this PR?

**Comment by nvhbk16k53** [comment]
He fixes my mistake from previous changes.

**Comment by metadoggo** [comment]
Fantastic! Let's merge!

**Pull request merged**
